version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium

  selenium:
    image: selenium/standalone-chrome:latest